### ISSUE TITLE
[EUSM] Products for some service points not showing on the app even though they are available on web

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-eusm#136]
When users log into the app, and conduct sync. Locations and service points are showing on the app. However, some service points are missing the products associated with them. This is happening for old (not newly created service points). These products are shown on the service point profile on the web (see screenshots below) but are not visible on android.
(could be related to #135)

On android: 
![image (19)](https://github.com/opensrp/opensrp-client-eusm/assets/58034047/01b20ab8-5597-41eb-92d9-8611fc25f831)

On web:
![image (20)](https://github.com/opensrp/opensrp-client-eusm/assets/58034047/d71ec465-6452-4171-b1bf-765eb6d47c61)

**Acceptance criteria**
- [ ] Products should show on the app on the service points they are assigned.

**Comment by hilpitome** [comment]
This was fixed by reposting the plans mentioned [here](https://github.com/opensrp/opensrp-client-eusm/issues/133#issuecomment-1849740618). However the service points **Dreah Ambato Boeny** and  `CISCO Mananara Avaratra `are missing products. I have searched for all the plans that are still active under the **BOENY** and **ANALANJIROFO** regions respectively and reposted them as well. This is in order to regenerate the relevant tasks. 
I am unable to verify at the moment that this worked because I have encountered login issues.
The login error being `You are currently not assigned to a mission. Please ask the EUSM administrators.`

**Comment by AnnieMungai** [comment]
@hilpitome as we observed - newly created products are showing correctly on the app. However, some of the already existing products need to be edited and then saved again for them to show on the app when the user performs a sync (they show as _product_check_ without showing the actual product).

**Comment by AnnieMungai** [comment]
@hilpitome
- [ ] I opened a service point and all the already exisiting products were not showing but they showed after some time - there is some lag (see screen shot below). - not sure whether it is an issue of a slow server. 
- [ ]  ![image](https://github.com/opensrp/opensrp-client-eusm/assets/58034047/082a1f94-afe3-4be1-b0c4-1c7c44f030ec)
- [x] Newly created products are showing on the app - LGTM!
- [ ] We seem to have lost the beneficiaries check (see screen shots above).

**Comment by Naima-Bashir** [comment]
@AnnieMungai @hilpitome This has also failed QA. I have added products on the two service points on web but since the actual service points aren't showing, the products are not there as well

**Comment by AnnieMungai** [comment]
The 2 service points can showing as seen on: https://github.com/opensrp/opensrp-client-eusm/issues/137#issuecomment-1921497006

LGTM!
