### ISSUE TITLE
Create default image for a product when no product image is uploaded to product catalogue

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#19]
Default product image would be displayed [here](https://marvelapp.com/prototype/1296hh24/screen/71758788) and [here](https://marvelapp.com/prototype/1296hh24/screen/71787697) if no product image exists for that product in the catalogue.

**Comment by cafootitt** [comment]
Can we get this by the end of this week, so COB on 27 Nov?

**Comment by rowo** [comment]
If we have this time frame (i.e. 2 days actually bc of Thanksgiving), I'm thinking we have to go with the current UNICEF product catalogue approach since there isn't time to get buy in on any new standard. This would mean some blue text like so: https://supply.unicef.org/s0969027.html

**Comment by rowo** [comment]
@cafootitt I added images to the [service point inventory list view](https://marvelapp.com/prototype/1296hh24/screen/71758788/handoff) and [item detail view](https://marvelapp.com/prototype/1296hh24/screen/71758789/handoff) with the assets available to download. If the image in Android are a different proportional size, the engineer working on this should let me know and I can update the image (since it's important with the border being exact.

**Comment by cafootitt** [comment]
Thanks, looks good.
